name: CI-RS

on:
  push:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  # Set more verbose terminal output
  CARGO_TERM_VERBOSE: true
  RUST_BACKTRACE: 1

# Cancel old builds on new commit for same workflow + branch/PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci-rs:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        rust-toolchain:
          - nightly

    steps:
      - name: Get source code
        uses: actions/checkout@v3

      - name: Setup ${{ matrix.rust-toolchain }} rust toolchain with caching
        uses: brndnmtthws/rust-action@v1
        with:
          toolchain: ${{ matrix.rust-toolchain }}
          components: rustfmt, clippy
          enable-sccache: "true"

      - name: Install Gstreamer
        run: brew install gstreamer gst-plugins-base gst-plugins-good gst-plugins-bad gst-plugins-ugly gst-libav gst-rtsp-server gst-editing-services
        
      - name: Install Gstreamer livekit plugin
        run: sudo sh build-livekit-gstreamer-macos.sh
        
      - name: Build
        run: cargo build

      - name: Test
        run: cargo test

      # - name: Lint
      #   run: cargo fmt --all -- --check
        # && cargo clippy --verbose -- -D warnings

